### PR TITLE
First implementation of a timeTrack functionality

### PR DESCRIPTION
**Pull request by HugoCrd**
Hi,

We discussed with @renaudboutet about a Time Tracking functionality built in ```logmatic-js```.
This is not an easy subject, but I came up with a (maybe naive) implementation which seems to work for our use case. 

:warning: This will work only for a single page application because Logmatic is not unloaded from DOM throu navigation.

I would be happy to discuss this here.

Use this functionnality like this : 
```
logmatic.init('<Your API key>');
logmatic.trackTime([step, [delay, [context, [message]]]]);
```
e.g.
```
logmatic.init('abcdef12345');
logmatic.trackTime(10*1000, 3*60*1000, {some: stuff}, "User time tracking");
```

This will send Logmatic a log containing ```context``` and ```message```every ```delay```ms. 
```context``` will be added a ```duration```attribute which contains the number of ms spent by user on the app. ```duration```is a multiple of ```step```.

### CODE REVIEW

**Comment by HugoCrd** [comment]
I thought about this this weekend. I think the idea is still relevant for standard websites (in opposition to single page apps). 
We would have to add a ```beforeunload``` listener which would send a last event before closing the page.

**Comment by renaudboutet** [comment]
Hi Hugo,

I just reviewed your pull request. This is interesting.

Right now you are adding the notion of step and delay, we were expecting to have only the notion of delay. However, after taking some time to think about it I understand that you need the "step" to know if the user is here or not...

However, before merging I would like to know if it is possible to:
- Add the "beforeunload" listener
- Convince me that resetting the timer whenever the user moves does not hurt too much the performances... :)
     => We think that it is probably better to not have the resetTimers but changing the timestamp of the last action for instance. This timestamp could be checked at the end of each step interval.

To finish, here are the 1 other improvement we would like to add after you:
- Beeing able to change the context on-the-fly
    => So we can know which view the user is seeing for instance in dynamic page

Please tell me what do you want to do.
We can also call  each other. :)

**Comment by renaudboutet** [comment]
Just to insist on this. I think the queuetime can be improved by having a startTimestamp and to compute the time you simply subtract the current time with the start time.

This could remove all the resets you have today by adding a second variable: lastActionTime for instance.

If you follow me.... :)

**Comment by HugoCrd** [comment]
> However, before merging

Please do not merge this, I just wrote this so we can discuss time tracking. Not sure it's a good implem yet.

> Add the "beforeunload" listener

Yeah, I think we need to do something like this. Thing is I don't know if it's possible to send an xhr request just before closing **and being sure it has been delivered**. Do you have any idea?

> Convince me that resetting the timer whenever the user moves does not hurt too much the performances... :) => We think that it is probably better to not have the resetTimers but changing the timestamp of the last action for instance. This timestamp could be checked at the end of each step interval.

Not convinced myself your idea may be better, I got a problem with observing so much things in the same time anyway...

> Beeing able to change the context on-the-fly

We need to have this too before I try this in production, cause we want to track usage by project/module (same mechanism as the page example)

> startTimestamp and to compute the time you simply subtract the current time with the start time

Yes Timestamps is a good idea. Will do.

**Comment by gpolaert** [comment]
@HugoCrd do you develop something to handle that feature. Is still opened for you?

**Pull request closed without merging**
